name: KNIME

channels:
  - nodefaults

dependencies:
  - python=3.9
  - anaconda::joblib=1.2.0
  - anaconda::scipy=1.11.3
  - anaconda::pandas=2.1.1
  - anaconda::scikit-learn=1.3.0
  - anaconda::git=2.40.1
  - conda-forge::matplotlib=3.8.0
  - conda-forge::pyarrow=11.0.0
  - conda-forge::py4j=0.10.9.7
  - pip
  - pip:
    - numpy==1.26.2 
    - pillow==10.0.1
    - kaleido==0.2.1
    - plotly==5.18.0
    - shap==0.44.0
    - python-javabridge
    - python-weka-wrapper3
    - git+https://github.com/jundongl/scikit-feature.git
    